--- 
javascripts: 
- base: 
  - jrails
  - swfobject
  - application
  - event_calendar
  - cufon-yui		
  - jquery.color-RGBa-patch
- secondary:
  - magicline
  - jquery.toggleformtext
  - easySlider1.5
stylesheets: 
- base: 
  - print
  - screen
  - ie
  - front
  - event_calendar
  - application
  - admin
  - magicline

