--- 
javascripts: 
- base: 
  - jrails
  - swfobject
  - application
  - event_calendar
  - cufon-yui		
  - autoload
  - reflection
  - jquery.color-RGBa-patch
  - nice_fonts
  - magicline
  - jquery.toggleformtext
  - jcarousellite
  - jquery.prettyPhoto

stylesheets: 
- base: 
  - print
  - screen
  - ie
  - front
  - event_calendar
  - application
  - admin
  - magicline
  - prettyPhoto

