development:
  bucket: granadainsider-development
  access_key_id: AKIAI7DG2I3UGHEC6FKA
  secret_access_key: 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

test:
  bucket: s3.engelvoelkersnewportbeach.com
  access_key_id: AKIAI7DG2I3UGHEC6FKA
  secret_access_key: 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

production:
  bucket: granadainsider-development
  access_key_id: AKIAI7DG2I3UGHEC6FKA
  secret_access_key: 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
